version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: 'always'
    ports:
      - '5432:5432'
    networks:
      - postgres
    build:
      context: ./

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  postgres:
