version: '3.8'

services:

  db:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    ports:
      - 8080:8080
