# This is a basic workflow to help you get started with Actions

name: PostgreSQL

# source:
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
#
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  container-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: init
      run: psql -v ON_ERROR_STOP=1 -f pg_create_redim_user.sql
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: install
      run: psql -v ON_ERROR_STOP=1 -f install.sql
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: redim
        PGPASSWORD: abcd1234

    - name: run tests
      run: psql -v ON_ERROR_STOP=1 -f pg_unit_test.sql
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: postgres
        PGUSER: redim
        PGPASSWORD: abcd1234
